// <auto-generated />
using System;
using CG.DVDCentral.PL2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CG.DVDCentral.PL2.Migrations
{
    [DbContext(typeof(DVDCentralEntities))]
    [Migration("20240206041410_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CG.DVDCentral.PL2.Entities.tblCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tblCart");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2400b3dc-c062-46d5-a158-627e684a4d6a"),
                            UserId = new Guid("5bbe6f5f-a240-4114-b1ee-7628bbcba23a")
                        },
                        new
                        {
                            Id = new Guid("7782f567-b3c5-48d4-b088-720abce168d7"),
                            UserId = new Guid("dd5c9fef-1c98-4272-8311-d809ff34ca8a")
                        });
                });

            modelBuilder.Entity("CG.DVDCentral.PL2.Entities.tblCartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("MovieId");

                    b.ToTable("tblCartItem");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e9fcfff-8ba9-4041-8aeb-0b34f76eac2f"),
                            CartId = new Guid("2400b3dc-c062-46d5-a158-627e684a4d6a"),
                            MovieId = new Guid("d25b5bd5-5fbd-4073-8dd1-9161cd7452a4"),
                            Qty = 1
                        },
                        new
                        {
                            Id = new Guid("966c0d44-f1e2-4bd5-ba96-cebd41814e63"),
                            CartId = new Guid("2400b3dc-c062-46d5-a158-627e684a4d6a"),
                            MovieId = new Guid("2241f40d-d254-4c93-b886-a6a1353f0d86"),
                            Qty = 2
                        },
                        new
                        {
                            Id = new Guid("38b7a04e-4dae-4e68-a35e-cc4d660ae83a"),
                            CartId = new Guid("7782f567-b3c5-48d4-b088-720abce168d7"),
                            MovieId = new Guid("2241f40d-d254-4c93-b886-a6a1353f0d86"),
                            Qty = 1
                        });
                });

            modelBuilder.Entity("CG.DVDCentral.PL2.Entities.tblCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZIP")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id")
                        .HasName("PK_tblCustomer_Id");

                    b.ToTable("tblCustomer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1205689-0a58-4006-bfb2-b19c7b52fe3c"),
                            Address = "453 Oak Street",
                            City = "Fond du Lac",
                            FirstName = "Steve",
                            LastName = "Marin",
                            Phone = "9205879797",
                            State = "WI",
                            UserId = new Guid("5bbe6f5f-a240-4114-b1ee-7628bbcba23a"),
                            ZIP = "54935"
                        },
                        new
                        {
                            Id = new Guid("e24b670d-cb9b-474a-bfac-2c98c9ec7df7"),
                            Address = "987 Willow Road",
                            City = "Slinger",
                            FirstName = "John",
                            LastName = "Doro",
                            Phone = "9202623345",
                            State = "WI",
                            UserId = new Guid("dd5c9fef-1c98-4272-8311-d809ff34ca8a"),
                            ZIP = "56495"
                        },
                        new
                        {
                            Id = new Guid("060c9614-0bfb-4630-bc66-07c146ab5418"),
                            Address = "159 Johnson Avenue",
                            City = "Allenton",
                            FirstName = "Brian",
                            LastName = "Foote",
                            Phone = "9202623415",
                            State = "WI",
                            UserId = new Guid("f9a65374-f511-4046-8553-cf63d00daac1"),
                            ZIP = "53142"
                        });
                });

            modelBuilder.Entity("CG.DVDCentral.PL2.Entities.tblDirector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblDirector_Id");

                    b.ToTable("tblDirector", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2b9a6f42-7740-4152-b72e-da86b3901c5a"),
                            FirstName = "John",
                            LastName = "Avildsen"
                        },
                        new
                        {
                            Id = new Guid("eba15250-036b-4098-af12-0d14050851f6"),
                            FirstName = "Steven",
                            LastName = "Spielberg"
                        },
                        new
                        {
                            Id = new Guid("29c237ef-1076-4b2d-b9cc-45353e9bba78"),
                            FirstName = "Rob",
                            LastName = "Reiner"
                        },
                        new
                        {
                            Id = new Guid("b37b2ac3-cb99-4e46-811a-fa721f1710ef"),
                            FirstName = "George",
                            LastName = "Lucas"
                        },
                        new
                        {
                            Id = new Guid("ab2d1a48-cc2a-4ac9-89a3-868cae16ce3b"),
                            FirstName = "Clint",
                            LastName = "Eastwood"
                        },
                        new
                        {
                            Id = new Guid("4b72b3ae-d2b6-443c-9a23-b984aaba650f"),
                            FirstName = "Other",
                            LastName = "Other"
                        });
                });

            modelBuilder.Entity("CG.DVDCentral.PL2.Entities.tblFormat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblFormat_Id");

                    b.ToTable("tblFormat", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("80506d2d-b654-45dc-96bb-88ab49b709dc"),
                            Description = "VHS"
                        },
                        new
                        {
                            Id = new Guid("7e136a2c-77a9-4940-81ac-a4858174b118"),
                            Description = "DVD"
                        },
                        new
                        {
                            Id = new Guid("c5df5222-2ee1-471e-964b-2acafebd686d"),
                            Description = "Blu-Ray"
                        },
                        new
                        {
                            Id = new Guid("62f2e0e0-bbd9-49ab-a43e-47d55c0541a1"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("CG.DVDCentral.PL2.Entities.tblGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblGenre_Id");

                    b.ToTable("tblGenre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("72e500dd-f4ee-4ae9-a610-7d58adbfeb64"),
                            Description = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("f4a5680d-7361-4970-9a06-7c9377b86efb"),
                            Description = "Action"
                        },
                        new
                        {
                            Id = new Guid("609e10d0-704c-40b5-b77d-7e8f375f9cc3"),
                            Description = "Sci-Fi"
                        },
                        new
                        {
                            Id = new Guid("9f43c1e1-730b-43e8-856d-73fb0cd16f73"),
                            Description = "Horror"
                        },
                        new
                        {
                            Id = new Guid("6ecd3242-7da4-4118-951e-f594c6c6fe72"),
                            Description = "Romance"
                        },
                        new
                        {
                            Id = new Guid("7ea9d043-9d88-4d77-a8dc-b3b9d71ae3ac"),
                            Description = "Documentary"
                        },
                        new
                        {
                            Id = new Guid("4617915c-ba97-431e-876f-bc30b58d8673"),
                            Description = "Musical"
                        },
                        new
                        {
                            Id = new Guid("30865c0f-9643-4236-8aee-3ee2d473098e"),
                            Description = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("9051a2a0-1b1c-4b28-9e30-b003c61200f6"),
                            Description = "Western"
                        },
                        new
                        {
                            Id = new Guid("bb016b72-a7d9-449e-8b24-da069541cccb"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("CG.DVDCentral.PL2.Entities.tblMovie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("DirectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("InStkQty")
                        .HasColumnType("int");

                    b.Property<Guid>("RatingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblMovie_Id");

                    b.HasIndex("DirectorId");

                    b.HasIndex("FormatId");

                    b.HasIndex("RatingId");

                    b.ToTable("tblMovie", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d25b5bd5-5fbd-4073-8dd1-9161cd7452a4"),
                            Cost = 6.9900000000000002,
                            Description = "Rocky is a 1976 American sports drama film directed by John G. Avildsen, written by and starring Sylvester Stallone.",
                            DirectorId = new Guid("2b9a6f42-7740-4152-b72e-da86b3901c5a"),
                            FormatId = new Guid("80506d2d-b654-45dc-96bb-88ab49b709dc"),
                            ImagePath = "Rocky.jpg",
                            InStkQty = 2,
                            RatingId = new Guid("aef9f710-2cfc-42df-b9d1-816d0cefa21f"),
                            Title = "Rocky"
                        },
                        new
                        {
                            Id = new Guid("c8926029-a577-4b2a-8650-85d0bf213aaf"),
                            Cost = 6.9900000000000002,
                            Description = "Other",
                            DirectorId = new Guid("2b9a6f42-7740-4152-b72e-da86b3901c5a"),
                            FormatId = new Guid("80506d2d-b654-45dc-96bb-88ab49b709dc"),
                            ImagePath = "Rocky.jpg",
                            InStkQty = 2,
                            RatingId = new Guid("aef9f710-2cfc-42df-b9d1-816d0cefa21f"),
                            Title = "Other"
                        },
                        new
                        {
                            Id = new Guid("2241f40d-d254-4c93-b886-a6a1353f0d86"),
                            Cost = 8.9900000000000002,
                            Description = "Jaws is a 1975 American thriller film directed by Steven Spielberg and based on the Peter Benchley 1974 novel of the same name.",
                            DirectorId = new Guid("eba15250-036b-4098-af12-0d14050851f6"),
                            FormatId = new Guid("7e136a2c-77a9-4940-81ac-a4858174b118"),
                            ImagePath = "Jaws1.jpg",
                            InStkQty = 1,
                            RatingId = new Guid("49bd933f-e667-4e4f-b2cc-8abbb2a92020"),
                            Title = "Jaws"
                        },
                        new
                        {
                            Id = new Guid("25161eb2-d757-4bc7-b620-7769bff8e263"),
                            Cost = 12.5,
                            Description = "The Princess Bride is a 1987 American fantasy adventure comedy film directed and co-produced by Rob Reiner, starring Cary Elwes, Robin Wright, Mandy Patinkin, Chris Sarandon, Wallace Shawn, André the Giant, and Christopher Guest.",
                            DirectorId = new Guid("29c237ef-1076-4b2d-b9cc-45353e9bba78"),
                            FormatId = new Guid("c5df5222-2ee1-471e-964b-2acafebd686d"),
                            ImagePath = "PrincessBride.jpg",
                            InStkQty = 4,
                            RatingId = new Guid("38b5aa50-ad63-45ba-a2d9-9b30c0309e3f"),
                            Title = "The Princess Bride"
                        },
                        new
                        {
                            Id = new Guid("d4d6eb05-e971-417e-a657-7d2399d2f3e5"),
                            Cost = 10.5,
                            Description = "Indiana Jones and the Last Crusade is a 1989 American action-adventure film directed by Steven Spielberg, from a story co-written by executive producer George Lucas.",
                            DirectorId = new Guid("b37b2ac3-cb99-4e46-811a-fa721f1710ef"),
                            FormatId = new Guid("c5df5222-2ee1-471e-964b-2acafebd686d"),
                            ImagePath = "IndianaJonesLastCrusade.jpg",
                            InStkQty = 2,
                            RatingId = new Guid("08eaa2b2-0aa7-4c79-90e6-096739566c51"),
                            Title = "Indiana Jones and the Last Crusade"
                        },
                        new
                        {
                            Id = new Guid("ff5df706-2968-4307-9f18-560e240ecd89"),
                            Cost = 7.5,
                            Description = "Star Wars: Episode IV – A New Hope is a 1977 American epic space-opera film written and directed by George Lucas, produced by Lucasfilm and distributed by 20th Century Fox.",
                            DirectorId = new Guid("eba15250-036b-4098-af12-0d14050851f6"),
                            FormatId = new Guid("7e136a2c-77a9-4940-81ac-a4858174b118"),
                            ImagePath = "StarWarsNewHope.jpg",
                            InStkQty = 1,
                            RatingId = new Guid("49bd933f-e667-4e4f-b2cc-8abbb2a92020"),
                            Title = "Star Wars: Episode IV – A New Hope"
                        },
                        new
                        {
                            Id = new Guid("bcb0624c-8aa7-4e90-919c-a062cf9ba803"),
                            Cost = 9.9900000000000002,
                            Description = "Pale Rider is a 1985 American Western film produced and directed by Clint Eastwood, who also stars in the lead role.",
                            DirectorId = new Guid("eba15250-036b-4098-af12-0d14050851f6"),
                            FormatId = new Guid("7e136a2c-77a9-4940-81ac-a4858174b118"),
                            ImagePath = "PaleRider.jpg",
                            InStkQty = 1,
                            RatingId = new Guid("49bd933f-e667-4e4f-b2cc-8abbb2a92020"),
                            Title = "Pale Rider"
                        });
                });

            modelBuilder.Entity("CG.DVDCentral.PL2.Entities.tblMovieGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblMovieGenre_Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MovieId");

                    b.ToTable("tblMovieGenre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55743949-a0f5-4cc0-aa4f-ee8cde831053"),
                            GenreId = new Guid("609e10d0-704c-40b5-b77d-7e8f375f9cc3"),
                            MovieId = new Guid("d25b5bd5-5fbd-4073-8dd1-9161cd7452a4")
                        },
                        new
                        {
                            Id = new Guid("558e1efc-ca95-44e1-8aa0-f76b66de1b2a"),
                            GenreId = new Guid("9f43c1e1-730b-43e8-856d-73fb0cd16f73"),
                            MovieId = new Guid("d25b5bd5-5fbd-4073-8dd1-9161cd7452a4")
                        },
                        new
                        {
                            Id = new Guid("07ede865-4f1a-4f04-be89-6258d222cbba"),
                            GenreId = new Guid("7ea9d043-9d88-4d77-a8dc-b3b9d71ae3ac"),
                            MovieId = new Guid("d25b5bd5-5fbd-4073-8dd1-9161cd7452a4")
                        },
                        new
                        {
                            Id = new Guid("a9043a96-ab5d-4024-8c26-af00df439ef3"),
                            GenreId = new Guid("609e10d0-704c-40b5-b77d-7e8f375f9cc3"),
                            MovieId = new Guid("2241f40d-d254-4c93-b886-a6a1353f0d86")
                        },
                        new
                        {
                            Id = new Guid("85172f3f-f683-4bcf-987a-f49715e3a54c"),
                            GenreId = new Guid("9f43c1e1-730b-43e8-856d-73fb0cd16f73"),
                            MovieId = new Guid("2241f40d-d254-4c93-b886-a6a1353f0d86")
                        },
                        new
                        {
                            Id = new Guid("67b9e4df-32bf-49a0-a61a-29012ad5ab5e"),
                            GenreId = new Guid("72e500dd-f4ee-4ae9-a610-7d58adbfeb64"),
                            MovieId = new Guid("25161eb2-d757-4bc7-b620-7769bff8e263")
                        },
                        new
                        {
                            Id = new Guid("e99eb1e7-7835-4e2e-a539-deac7d17bd70"),
                            GenreId = new Guid("f4a5680d-7361-4970-9a06-7c9377b86efb"),
                            MovieId = new Guid("25161eb2-d757-4bc7-b620-7769bff8e263")
                        },
                        new
                        {
                            Id = new Guid("416ac5f4-d0a4-483c-8032-a571908a74ee"),
                            GenreId = new Guid("7ea9d043-9d88-4d77-a8dc-b3b9d71ae3ac"),
                            MovieId = new Guid("25161eb2-d757-4bc7-b620-7769bff8e263")
                        },
                        new
                        {
                            Id = new Guid("2ee0157b-1ca4-4570-885a-ed023397b0e6"),
                            GenreId = new Guid("9f43c1e1-730b-43e8-856d-73fb0cd16f73"),
                            MovieId = new Guid("d4d6eb05-e971-417e-a657-7d2399d2f3e5")
                        },
                        new
                        {
                            Id = new Guid("a18517a9-08ab-421b-ad0a-a6539cf11097"),
                            GenreId = new Guid("7ea9d043-9d88-4d77-a8dc-b3b9d71ae3ac"),
                            MovieId = new Guid("d4d6eb05-e971-417e-a657-7d2399d2f3e5")
                        },
                        new
                        {
                            Id = new Guid("8bf8f228-798d-4b06-9feb-916cbd88491a"),
                            GenreId = new Guid("9f43c1e1-730b-43e8-856d-73fb0cd16f73"),
                            MovieId = new Guid("ff5df706-2968-4307-9f18-560e240ecd89")
                        },
                        new
                        {
                            Id = new Guid("2ed49b42-7483-435e-aeff-3af4fc6f3b8c"),
                            GenreId = new Guid("4617915c-ba97-431e-876f-bc30b58d8673"),
                            MovieId = new Guid("ff5df706-2968-4307-9f18-560e240ecd89")
                        },
                        new
                        {
                            Id = new Guid("817e0ad7-676d-42a8-ab26-99eac1b2879c"),
                            GenreId = new Guid("30865c0f-9643-4236-8aee-3ee2d473098e"),
                            MovieId = new Guid("bcb0624c-8aa7-4e90-919c-a062cf9ba803")
                        });
                });

            modelBuilder.Entity("CG.DVDCentral.PL2.Entities.tblOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ShipDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblOrder_Id");

                    b.ToTable("tblOrder", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a5be276-0690-44f9-be15-f839d1b37a30"),
                            CustomerId = new Guid("e24b670d-cb9b-474a-bfac-2c98c9ec7df7"),
                            OrderDate = new DateTime(2017, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2017, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("dd5c9fef-1c98-4272-8311-d809ff34ca8a")
                        },
                        new
                        {
                            Id = new Guid("22aab2fb-96c1-4ae7-a04e-a1085e1cd99b"),
                            CustomerId = new Guid("060c9614-0bfb-4630-bc66-07c146ab5418"),
                            OrderDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2021, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("dd5c9fef-1c98-4272-8311-d809ff34ca8a")
                        },
                        new
                        {
                            Id = new Guid("9b401be4-2eec-42af-9c56-83a987a8f254"),
                            CustomerId = new Guid("060c9614-0bfb-4630-bc66-07c146ab5418"),
                            OrderDate = new DateTime(2022, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2022, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("f9a65374-f511-4046-8553-cf63d00daac1")
                        });
                });

            modelBuilder.Entity("CG.DVDCentral.PL2.Entities.tblOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblOrderItem_Id");

                    b.ToTable("tblOrderItem", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55b9576f-83b4-49d6-982c-a595af9e797a"),
                            Cost = 8.9900000000000002,
                            MovieId = new Guid("d25b5bd5-5fbd-4073-8dd1-9161cd7452a4"),
                            OrderId = new Guid("1a5be276-0690-44f9-be15-f839d1b37a30"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("994eb40f-0762-4856-acc4-aea47cd0a86b"),
                            Cost = 9.9900000000000002,
                            MovieId = new Guid("2241f40d-d254-4c93-b886-a6a1353f0d86"),
                            OrderId = new Guid("1a5be276-0690-44f9-be15-f839d1b37a30"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("b50e7767-9c3a-4cc3-8bce-d60b61465f03"),
                            Cost = 10.99,
                            MovieId = new Guid("2241f40d-d254-4c93-b886-a6a1353f0d86"),
                            OrderId = new Guid("22aab2fb-96c1-4ae7-a04e-a1085e1cd99b"),
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("CG.DVDCentral.PL2.Entities.tblRating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblRating_Id");

                    b.ToTable("tblRating", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aef9f710-2cfc-42df-b9d1-816d0cefa21f"),
                            Description = "G"
                        },
                        new
                        {
                            Id = new Guid("49bd933f-e667-4e4f-b2cc-8abbb2a92020"),
                            Description = "PG-13"
                        },
                        new
                        {
                            Id = new Guid("38b5aa50-ad63-45ba-a2d9-9b30c0309e3f"),
                            Description = "PG"
                        },
                        new
                        {
                            Id = new Guid("08eaa2b2-0aa7-4c79-90e6-096739566c51"),
                            Description = "R"
                        },
                        new
                        {
                            Id = new Guid("df0d7692-d1bf-426e-a1f5-3d2fc3b0d592"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("CG.DVDCentral.PL2.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(28)
                        .IsUnicode(false)
                        .HasColumnType("varchar(28)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5bbe6f5f-a240-4114-b1ee-7628bbcba23a"),
                            FirstName = "Steve",
                            LastName = "Marin",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserName = "smarin"
                        },
                        new
                        {
                            Id = new Guid("dd5c9fef-1c98-4272-8311-d809ff34ca8a"),
                            FirstName = "John",
                            LastName = "Doro",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserName = "jdoro"
                        },
                        new
                        {
                            Id = new Guid("f9a65374-f511-4046-8553-cf63d00daac1"),
                            FirstName = "Brian",
                            LastName = "Foote",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserName = "bfoote"
                        });
                });

            modelBuilder.Entity("CG.DVDCentral.PL2.Entities.tblCart", b =>
                {
                    b.HasOne("CG.DVDCentral.PL2.tblUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CG.DVDCentral.PL2.Entities.tblCartItem", b =>
                {
                    b.HasOne("CG.DVDCentral.PL2.Entities.tblCart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CG.DVDCentral.PL2.Entities.tblMovie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CG.DVDCentral.PL2.Entities.tblMovie", b =>
                {
                    b.HasOne("CG.DVDCentral.PL2.Entities.tblDirector", "Director")
                        .WithMany("tblMovies")
                        .HasForeignKey("DirectorId")
                        .IsRequired()
                        .HasConstraintName("fk_tblMovie_DirectorId");

                    b.HasOne("CG.DVDCentral.PL2.Entities.tblFormat", "Format")
                        .WithMany("tblMovies")
                        .HasForeignKey("FormatId")
                        .IsRequired()
                        .HasConstraintName("fk_tblMovie_FormatId");

                    b.HasOne("CG.DVDCentral.PL2.Entities.tblRating", "Rating")
                        .WithMany("tblMovies")
                        .HasForeignKey("RatingId")
                        .IsRequired()
                        .HasConstraintName("fk_tblMovie_RatingId");

                    b.Navigation("Director");

                    b.Navigation("Format");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("CG.DVDCentral.PL2.Entities.tblMovieGenre", b =>
                {
                    b.HasOne("CG.DVDCentral.PL2.Entities.tblGenre", "Genre")
                        .WithMany("tblMovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblMovieGenre_GenreId");

                    b.HasOne("CG.DVDCentral.PL2.Entities.tblMovie", "Movie")
                        .WithMany("tblMovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblMovieGenre_MovieId");

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CG.DVDCentral.PL2.Entities.tblDirector", b =>
                {
                    b.Navigation("tblMovies");
                });

            modelBuilder.Entity("CG.DVDCentral.PL2.Entities.tblFormat", b =>
                {
                    b.Navigation("tblMovies");
                });

            modelBuilder.Entity("CG.DVDCentral.PL2.Entities.tblGenre", b =>
                {
                    b.Navigation("tblMovieGenres");
                });

            modelBuilder.Entity("CG.DVDCentral.PL2.Entities.tblMovie", b =>
                {
                    b.Navigation("tblMovieGenres");
                });

            modelBuilder.Entity("CG.DVDCentral.PL2.Entities.tblRating", b =>
                {
                    b.Navigation("tblMovies");
                });
#pragma warning restore 612, 618
        }
    }
}
